use sha2::{Digest, Sha256};
use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest[..]);
    out
}

fn fmt_u8_array(bytes: &[u8]) -> String {
    let mut out = String::from("[");
    for (idx, b) in bytes.iter().enumerate() {
        if idx != 0 {
            out.push_str(", ");
        }
        out.push_str(&b.to_string());
    }
    out.push(']');
    out
}

fn repo_root_from_manifest_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .ancestors()
        .nth(4)
        .expect("web/build.rs: expected web crate to be at app/crates/platforms/web")
        .to_path_buf()
}

fn read_optional_bytes(path: &Path, label: &str) -> Vec<u8> {
    match fs::read(path) {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            println!(
                "cargo:warning=web/build.rs: {label} is absent ({}); using empty bytes",
                path.display()
            );
            Vec::new()
        }
        Err(error) => panic!(
            "web/build.rs: failed to read {label} {}: {error}",
            path.display()
        ),
    }
}

fn write_proving_key_module(out_dir: &Path, keys: &[(&str, &Path, bool)]) {
    let mut contents = String::from(
        "// @generated by app/crates/platforms/web/build.rs\n// Do not edit manually.\n\n",
    );

    for (name, path, present) in keys {
        if *present {
            contents.push_str(&format!(
                "pub static {name}: &[u8] = include_bytes!(r#\"{}\"#);\n",
                path.display()
            ));
        } else {
            contents.push_str(&format!("pub static {name}: &[u8] = &[];\n"));
        }
    }

    let path = out_dir.join("proving_keys.rs");
    fs::write(&path, contents)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to write {}: {e}", path.display()));
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = repo_root_from_manifest_dir(&manifest_dir);

    let proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/policy_tx_2_2_proving_key.bin");
    let disclosure_proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/selectiveDisclosure_1_proving_key.bin");
    let payroll_proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/payroll_20_proving_key.bin");

    let profile = env::var("PROFILE").expect("PROFILE env var is set by Cargo");
    let circuits_out = repo_root.join("target/circuits-artifacts").join(&profile);

    if !circuits_out.is_dir() {
        println!(
            "cargo:warning=web/build.rs: circuit artifacts directory missing for PROFILE={profile}: {}; WASM/R1CS will be empty bytes",
            circuits_out.display()
        );
    }

    let wasm_path = circuits_out.join("policy_tx_2_2.wasm");
    let r1cs_path = circuits_out.join("policy_tx_2_2.r1cs");

    let disclosure_wasm_path = circuits_out.join("selectiveDisclosure_1.wasm");
    let disclosure_r1cs_path = circuits_out.join("selectiveDisclosure_1.r1cs");

    let payroll_wasm_path = circuits_out.join("payroll_20.wasm");
    let payroll_r1cs_path = circuits_out.join("payroll_20.r1cs");

    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-changed={}", proving_key_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        disclosure_proving_key_path.display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        payroll_proving_key_path.display()
    );
    println!("cargo:rerun-if-changed={}", wasm_path.display());
    println!("cargo:rerun-if-changed={}", r1cs_path.display());
    println!("cargo:rerun-if-changed={}", disclosure_wasm_path.display());
    println!("cargo:rerun-if-changed={}", disclosure_r1cs_path.display());
    println!("cargo:rerun-if-changed={}", payroll_wasm_path.display());
    println!("cargo:rerun-if-changed={}", payroll_r1cs_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let proving_key_bytes = read_optional_bytes(&proving_key_path, "proving key");
    let disclosure_proving_key_bytes =
        read_optional_bytes(&disclosure_proving_key_path, "disclosure proving key");
    let payroll_proving_key_bytes =
        read_optional_bytes(&payroll_proving_key_path, "payroll proving key");
    let wasm_bytes = read_optional_bytes(&wasm_path, "wasm");
    let r1cs_bytes = read_optional_bytes(&r1cs_path, "r1cs");
    let disclosure_wasm_bytes = read_optional_bytes(&disclosure_wasm_path, "disclosure wasm");
    let disclosure_r1cs_bytes = read_optional_bytes(&disclosure_r1cs_path, "disclosure r1cs");
    let payroll_wasm_bytes = read_optional_bytes(&payroll_wasm_path, "payroll wasm");
    let payroll_r1cs_bytes = read_optional_bytes(&payroll_r1cs_path, "payroll r1cs");

    let proving_key_hash = sha256(&proving_key_bytes);
    let disclosure_proving_key_hash = sha256(&disclosure_proving_key_bytes);
    let payroll_proving_key_hash = sha256(&payroll_proving_key_bytes);
    let wasm_hash = sha256(&wasm_bytes);
    let r1cs_hash = sha256(&r1cs_bytes);
    let disclosure_wasm_hash = sha256(&disclosure_wasm_bytes);
    let disclosure_r1cs_hash = sha256(&disclosure_r1cs_bytes);
    let payroll_wasm_hash = sha256(&payroll_wasm_bytes);
    let payroll_r1cs_hash = sha256(&payroll_r1cs_bytes);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    write_proving_key_module(
        &out_dir,
        &[
            (
                "POLICY_TX_2_2",
                &proving_key_path,
                !proving_key_bytes.is_empty(),
            ),
            (
                "SELECTIVE_DISCLOSURE_1",
                &disclosure_proving_key_path,
                !disclosure_proving_key_bytes.is_empty(),
            ),
            (
                "PAYROLL_20",
                &payroll_proving_key_path,
                !payroll_proving_key_bytes.is_empty(),
            ),
        ],
    );
    let out_path = out_dir.join("artifact_hashes.rs");

    let contents = format!(
        "\
// @generated by app/crates/platforms/web/build.rs
// Do not edit manually.

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_SHA256: [u8; 32] = {proving_key_hash};
pub const EXPECTED_POLICY_TX_2_2_WASM_SHA256: [u8; 32] = {wasm_hash};
pub const EXPECTED_POLICY_TX_2_2_R1CS_SHA256: [u8; 32] = {r1cs_hash};

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_LEN: usize = {proving_key_len};
pub const EXPECTED_POLICY_TX_2_2_WASM_LEN: usize = {wasm_len};
pub const EXPECTED_POLICY_TX_2_2_R1CS_LEN: usize = {r1cs_len};

pub const EXPECTED_SELECTIVE_DISCLOSURE_1_PROVING_KEY_SHA256: [u8; 32] = {disclosure_proving_key_hash};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_WASM_SHA256: [u8; 32] = {disclosure_wasm_hash};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_R1CS_SHA256: [u8; 32] = {disclosure_r1cs_hash};

pub const EXPECTED_SELECTIVE_DISCLOSURE_1_PROVING_KEY_LEN: usize = {disclosure_proving_key_len};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_WASM_LEN: usize = {disclosure_wasm_len};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_R1CS_LEN: usize = {disclosure_r1cs_len};

pub const EXPECTED_PAYROLL_20_PROVING_KEY_SHA256: [u8; 32] = {payroll_proving_key_hash};
pub const EXPECTED_PAYROLL_20_WASM_SHA256: [u8; 32] = {payroll_wasm_hash};
pub const EXPECTED_PAYROLL_20_R1CS_SHA256: [u8; 32] = {payroll_r1cs_hash};

pub const EXPECTED_PAYROLL_20_PROVING_KEY_LEN: usize = {payroll_proving_key_len};
pub const EXPECTED_PAYROLL_20_WASM_LEN: usize = {payroll_wasm_len};
pub const EXPECTED_PAYROLL_20_R1CS_LEN: usize = {payroll_r1cs_len};
",
        proving_key_hash = fmt_u8_array(&proving_key_hash),
        wasm_hash = fmt_u8_array(&wasm_hash),
        r1cs_hash = fmt_u8_array(&r1cs_hash),
        proving_key_len = proving_key_bytes.len(),
        wasm_len = wasm_bytes.len(),
        r1cs_len = r1cs_bytes.len(),
        disclosure_proving_key_hash = fmt_u8_array(&disclosure_proving_key_hash),
        disclosure_wasm_hash = fmt_u8_array(&disclosure_wasm_hash),
        disclosure_r1cs_hash = fmt_u8_array(&disclosure_r1cs_hash),
        disclosure_proving_key_len = disclosure_proving_key_bytes.len(),
        disclosure_wasm_len = disclosure_wasm_bytes.len(),
        disclosure_r1cs_len = disclosure_r1cs_bytes.len(),
        payroll_proving_key_hash = fmt_u8_array(&payroll_proving_key_hash),
        payroll_wasm_hash = fmt_u8_array(&payroll_wasm_hash),
        payroll_r1cs_hash = fmt_u8_array(&payroll_r1cs_hash),
        payroll_proving_key_len = payroll_proving_key_bytes.len(),
        payroll_wasm_len = payroll_wasm_bytes.len(),
        payroll_r1cs_len = payroll_r1cs_bytes.len(),
    );

    fs::write(&out_path, contents)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to write {}: {e}", out_path.display()));
}
